### PR TITLE
Added script to generate page for Suru icons

### PR DESCRIPTION
**Pull request by bhdouglass**
Created a script to generate a page for Suru Icons, also includes all the icons and the generated page. I opted not to include the ubuntu-themes repo as a submodule in case the screws with the build on read the docs. If that's not desirable I can change it.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
It appears that submodules are supported as part of the new configuration format. Good time to migrate? https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by bhdouglass** [comment]
Well, it wouldn't be necessary to generate the icons page with every docs update, so that's probably overkill for right now. Unless of course we change our icon set often.

**Comment by UniversalSuperBox** [comment]
How long does the generation take? As a rule I don't like generated files saved in version control.

**Comment by bhdouglass** [comment]
The generation doesn't take long, so you could probably add it to the build. And I agree with that rule, but it probably won't change enough to warrant big changes to the build process. But of course, I'll leave that up to you.

**Comment by UniversalSuperBox** [comment]
We absolutely need this, no doubt about that. I think that integrating this way will cause a couple problems though:

* Any constant text gets tossed into the translations... so we'll get translated icon names
* That's a lot of clone time we're adding...
* You're right, it's a waste of time to rebuild this on any change

Maybe the icons should be moved into another project ([Subprojects](https://docs.readthedocs.io/en/stable/subprojects.html)), that way we can rebuild them independently. Would only need a new repository, either of us can import it into Read the Docs and add it as a subproject.

**Comment by bhdouglass** [comment]
With the subproject do you get the navigation the same between them? If not it might make more sense to just make an html page.

**Comment by UniversalSuperBox** [comment]
Search is shared, we might have to do something a bit strange for navigation (the subproject goes at `docs.ubports.com/projects/icons/en/latest`, for example). Not a big deal.

**Comment by bhdouglass** [comment]
Ok, closing this PR and starting https://github.com/ubports/icon-docs

**Pull request closed without merging**
