### PR TITLE
Added content hub diagram & updated descriptions

### PR DESCRIPTION
**Pull request by bhdouglass**
I accidentally pushed changes that made the last PR closed: https://github.com/ubports/docs.ubports.com/pull/275

### CODE REVIEW

**Comment by bhdouglass** [comment]
@cibersheep that just broke everything... https://ci.ubports.com/job/docs.ubports.com/job/improve-contenthub-guide/3/artifact/_build/html/appdev/guides/contenthub.html

**Comment by cibersheep** [comment]
> @cibersheep that just broke everything... https://ci.ubports.com/job/docs.ubports.com/job/improve-contenthub-guide/3/artifact/_build/html/appdev/guides/contenthub.html

What I broke? Are you talking to me? I wait for you **outside**

:P 

You have a new svg test in your timeline

**Comment by bhdouglass** [comment]
Oh its on now @cibersheep ! ;P

**Comment by bhdouglass** [comment]
@cibersheep is amazing. @doniks this is ready to roll!

**Pull request merged**
