### PR TITLE
Update install.rst

### PR DESCRIPTION
**Pull request by PigCode**
Improve the installation process

### CODE REVIEW

**Comment by mymike00** [comment]
I don't think pressing the down volume is always needed. I'd rather add it as an option if just plugging doesn't work.

**Comment by PigCode** [comment]
> I don't think pressing the down volume is always needed. I'd rather add it as an option if just plugging doesn't work.

Meizu MX4 Android Edition must pressing the down volume

**Comment by mymike00** [comment]
something like "plug the usb cable. if nothing happens, disconnect the cable and reconnect it while keeping the volume down button pressed: some phones require that, some others don't"

Better solution is to test all the devices and find out which ones require the button pressed and which ones don't, but I'd take some more time...

**Comment by doniks** [comment]
Maybe like: On some devices (such as x) you need to do this. On other devices (such as y) do that.

Now a user with device z comes around, and should: we don't know for sure, but trying this or that are probably good suggestions

**Comment by doniks** [comment]
ping @PigCode

**Comment by doniks** [comment]
Seems the contributor has disappeared. I'm closing this for now. @PigCode  if you still/again want to fix this up, feel free to reopen!

**Pull request closed without merging**
