### PR TITLE
change in appdev section

### PR DESCRIPTION
**Pull request by lduboeuf**
hi,

Just simplify some docs in appdev section.
Added a short introduction on nativeapp section

### CODE REVIEW

**Comment by lduboeuf** [comment]
humm don't know with my olds commit appear in this PR ?!! Something i've wrongly done ?

**Comment by bhdouglass** [comment]
Yeah you probably want to move the commits that you actually want to merge over to a new branch or something.

**Comment by lduboeuf** [comment]
yes ,so will try another one, sorry

**Comment by bhdouglass** [comment]
No worries, it happens 🙂

**Pull request closed without merging**
