### PR TITLE
update zh_CN locales files by `msgmerge`

### PR DESCRIPTION
**Pull request by kuailexs**
after https://github.com/ubports/docs.ubports.com/pull/619

### CODE REVIEW

**Comment by doniks** [comment]
Shouldn't this happen via weblate?

**Comment by kuailexs** [comment]
> Shouldn't this happen via weblate?

this repository on weblate is closed

**Comment by kuailexs** [comment]
https://hosted.weblate.org/projects/ubports/

only  docs.ubports.com about page

**Comment by kuailexs** [comment]
There is no place to contribute translations

**Comment by doniks** [comment]
ah. yes. I see now. you're right. Thanks for pushing this even with lacking infrastructure!

**Review by doniks — APPROVED** [review]

**Pull request merged**
