### PR TITLE
Added content hub diagram & updated descriptions

### PR DESCRIPTION
**Pull request by bhdouglass**
Ping @cibersheep

### CODE REVIEW

**Comment by cibersheep** [comment]
Nice!

**Comment by bhdouglass** [comment]
Good idea, I swapped the png out for an svg. :+1: 

I'm not sure I want to subtitle the "My App" part, as I was focusing on what the peer is (especially being placed right below the `ContentHandler.*` section).

**Comment by doniks** [comment]
thanks, but actually now the svg doesn't seem to come out right ... or is it my browser? when I go here: https://ci.ubports.com/job/docs.ubports.com/job/PR-275/2/artifact/_build/html/appdev/guides/contenthub.html I can't properly read the labels on the diagram. something with the fonts

**Comment by bhdouglass** [comment]
I reverted back to the png, not sure why that is happening (maybe the build process is stripping something out of the svg?).

**Comment by cibersheep** [comment]
If you like, send it to me and I can take a look (or transform text to curves)

**Comment by bhdouglass** [comment]
I just sent it to you on telegram, thanks for looking at it!

**Pull request closed without merging**
