### PR TITLE
Initial sdk doc import

### PR DESCRIPTION
**Pull request by bhdouglass**
The docs still need lots of love (converting from html to rst has it's drawbacks), but at least it's here and we can say we are working on it.

### CODE REVIEW

**Comment by Flohack74** [comment]
@NeoTheThird are we good with this?

**Comment by bhdouglass** [comment]
@Flohack74  it's not ready just yet. I've got some improvements incoming

**Comment by bhdouglass** [comment]
@Flohack74 & @NeoTheThird ok, this is ready to go now. It's still got some warning but they probably need to be fixed in the docs rather than by my script.

**Comment by bhdouglass** [comment]
Here are the scripts used to generate the docs: https://github.com/bhdouglass/ubuntu-touch-sdk-api-scripts

**Comment by NeoTheThird** [comment]
Lgtm! Great work, Brian!

**Comment by bhdouglass** [comment]
Thanks!

**Pull request merged**
