### PR TITLE
Update Preparations.rst

### PR DESCRIPTION
**Pull request by ZGStuff**
just updated version numbers for ubuntu

### CODE REVIEW

**Comment by ZGStuff** [comment]
dang MORE updates? another one pull request it is

**Review by doniks — CHANGES_REQUESTED** [review]
I think it might be best to remove the whole "For example" sentence. 

It doesn't really convey any information. Especially since there is the other place here https://github.com/ubports/docs.ubports.com/pull/546. As it is written now it is bound to be regularly out of date.

**Review by doniks — CHANGES_REQUESTED** [review]
I think it might be best to remove the whole "For example" sentence.

**Comment by Flohack74** [comment]
Also , please make sure to run `update-translations.sh` on top level of the checkout with each change in an rst file, otherwise we cannot get the pot files updated and nothing can be translated :) - Instructions how to set up sphinx and other stuff should be in the README

**Comment by doniks** [comment]
> Also , please make sure to run `update-translations.sh` on top level of the checkout with each change in an rst file, otherwise we cannot get the pot files updated and nothing can be translated :) - Instructions how to set up sphinx and other stuff should be in the README

sounds like generic instructions?! Or is this specific for this PR? I'm worried if we have to explain this to every contributor, it will make contributions more complicated and even more sparse :worried:

**Comment by Flohack74** [comment]
@doniks yes its generic, but idk how we can make it more widespread.

**Comment by doniks** [comment]
cleaning up old open PR's ... in case you want to refloat this feel free to reopen!

**Pull request closed without merging**
