### PR TITLE
project folders refactoring refs #44

### PR DESCRIPTION
**Pull request by lduboeuf**
Here is a part of my proposition.
Porting and installing on the same topic.
remove `daily use` `advanced use` and put all of docs in `howtos`
did not work on app developpement structure yet

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Porting has nothing to do with installation, why would you document that together? Porting is about as difficult as development tasks come, while installation is a very easy process every user can (and has to) go through...

**Comment by lduboeuf** [comment]
this is your point of view :) . the final step is to install, so for me the same.

**Comment by lduboeuf** [comment]
anyway, don't mind if my PR not relevant.  maybe removing daily use and advanced use is ok

**Comment by lduboeuf** [comment]
ok maybe not accurate what i did. just the term "plaform" was a little ambigous, i understand that there is a need to simple end user install procedure and for devs a guide for porting new device. maybe we can only keep removing `daily use and advanced use` in favor of ` howtos` ?

**Comment by NeoTheThird** [comment]
In tech, [platform](https://en.wikipedia.org/wiki/Computing_platform) is an abstract term that describes to the environment of software and hardware. So my idea [when adding the platform category](https://github.com/ubports/docs.ubports.com/commit/3de4a9a5d15e8812c3a40fa0b13e2f6caf6a345b) was that it describes how the system is designed and works, while other sections are about how to work with that system. But due to some other changes, that got a little watered down, so we might have to revisit that...

**Comment by UniversalSuperBox** [comment]
It's my fault that Porting is under Platform right now, it should be in its own section. I misunderstood a previous pull request.

I don't like the idea of putting all information for using Ubuntu Touch under one HOWTO section. I forsee having a regular user's guide with some handy tips in it, not a Wiki-style free-for-all.

**Comment by lduboeuf** [comment]
alright, no problem for all that. still work to do though to make a newbie easy to start and understand all the picture. merry Christmas.

**Pull request closed without merging**
