### PR TITLE
Update Setting_up.rst

### PR DESCRIPTION
**Pull request by ZGStuff**
EVEN MORE UPDATING VERSION NUMBERS... just update the docs please

### CODE REVIEW

**Comment by doniks** [comment]
Can you elaborate a bit on how you tested this/ what the idea is behind these updates? Current version says that there is a difference between 18.04 and 20.04. With your PR you say there is no difference. Is that true? did you retest with both? is 22.04 really different from 20.04? how did you test that? ..

**Comment by ZGStuff** [comment]
mostly just rebuilding ubuntu touch but 22.04... heh
it kinda sucked
a lot of stuff broke

**Comment by doniks** [comment]
Uhm. So, you are basically saying that halium porting on 22.04 does NOT work?! I guess then we should NOT promote. Not at this time. Or am I misunderstanding something?!

**Comment by doniks** [comment]
ok. so I assume then that this is no longer needed. feel free to reopen if you see it differently

**Pull request closed without merging**
