### PR TITLE
A new look for the documentation

### PR DESCRIPTION
**Pull request by capsia37**
Hello,
this PR contains the new theme for the docs.
If you have any suggestions, feel free to comment :)

A preview is available at:

[https://ubports-docs-dev.readthedocs.io/](https://ubports-docs-dev.readthedocs.io/)

### CODE REVIEW

**Comment by lduboeuf** [comment]
Hey!, a very nice looking, congrats for the work.

**Comment by doniks** [comment]
Hey Capsia37

Sorry for the long wait. I just don't do much with graphics, so I thought ... let me wait for someone with more expertise to come around. And maybe 'corporate design' decisions are 'above my paygrade' (chuckle). But now it was so long that I thought, ok, you have to give them something and then go chase someone to make a call here. But now that I looked at it (and thanks for the hosted version because the jenkins ci version has a lot aesthetics messed up). It looks really nice! And you know what, even I can tell that it is a lot more in line with the corporate design of other ubports outlets! And you know what else, I just raised my paygrade (lol) and I'm approving this :D

Thanks Capsia37

I do have a few small remarks/questions/suggestions that I will post below. But if you disagree, or it's not (easily) possible, or whatever, I'm happy to merge as is. Even if you don't have time to reply at all, I would just merge it after a little while of silence.

**Review by doniks — APPROVED** [review]

**Comment by doniks** [comment]
image

**Comment by doniks** [comment]
Ok, here goes. A few points below. They all should be visible in the screenshot. Again, I'm happy to merge as is without any of these changes, but please look them through and consider them ...  yes/no/later/never ... all fine with me


1. the search panel top left seems to be cut off / underneath the content pane 
2. could we maybe increase the uhm contrast/distinction between the these (what do we call them, uhm) top level parts titles (ABOUT, USER GUIDE, etc) and the section headers (Introduction, Processes, Install Ubuntu Touch)
3. when I click on some of the later sections the table of contents on the left don't show where I am, since they scroll up. Ok, I guess this doesn't really have anything to do with your PR, but maybe you happen to know something about this. 
4. I'm wondering about the colors for the various boxes in the content. Upon first look I found the blue "notes" and the green code boxes stand out a little awkwardly. The more I look at it, the less I can still 'see' this. Maybe it's fine anyway. 
    * blue Notes. In my opinion, a 'Note' is something that actually should be *de*-emphasized. We stick it in the middle of the text, but essentially it's a footnote/the small print. I doesn't have draw the attention away from the text to itself. Right now it is quite prominent. Maybe some shade of grey would be enough
    * orange Warning. Looks fine as is. A warning *should* draw the attention and it does.
    * green code blocks. Upon first glance I found the green to clash a bit with the other colors ... but I don't have a good suggestion actually what else to do ... maybe you do
5. I find some of the items in the right pane a bit too prominent.
    * the Write for us block is bold orange on white on grey, with an additional large-font Edit on github, black on grey on white. I mean, I like to invite contributors, ... but maybe a little less 
    * The follow us on the bottom right is dark black on white. maybe we could make it in a dark grey instead?
6. depending on the width of the window I get a situation where the TOC on the left is glued close to the main content on it's right, and it has a lot of white space on the left. Not sure I'm expressing this right. I mean the proportion of a) the horizontal space from the left window border to 'Contributing to UBports' and b) the horizontal space from 'Contributing to UBports' to the main contents pane. It can even be 'worse' (more white space on the left) than in the screenshot - depending on window size. But maybe this is just in the nature of readthedocs. 
7. I'm using Ubuntu 20.10 on my laptop. Normally, I have the Appearance set to Dark in the System Settings. Apparently this causes Firefox to darken websites itself?! or maybe it tells websites that they should present themselves in a dark theme. Not sure how any of this works. Either way. Bottom line is I get a dark themed version of the docs and that messes up some things (strange colors, contrasts, logos not readable). This is an ultra-minor point, because anyway half of the internet's aesthetics are broken when you use dark modes. But I thought I mention it. Nowadays it's 'only' half of the internet. It used to be much worse, so I think the world is improving it's support for dark themes and maybe readthedocs has some out-of-the-box support for this. ok, enough rambling. this is really an ancillary point. Even IF you would decide to do anything about this, I would strongly suggest to NOT do anything in THIS PR, but follow that up at a later date.

**Comment by capsia37** [comment]
Hello @doniks and thank you for the review. I'm glad that you like the new theme.

I'm checking your points and I've solved 2,4 and 5, I'll send the commit soon. 
I'm not sure about what do you mean with 1.

The third point is related to the theme, I can file a bug upstream so that will be probably fixed in a future release of the theme.

The 6. point I think is intended, because if we enlarge the content we will have longer lines which are more difficult to read and if we enlarge the sidebars it would feel a bit out of scale, although scaling the sidebars just a bit might reduce the problem on bigger screens. I'll try out the possibilities and send some screenshots.

7. Yes, the RTD theme supports dark theme by default, we might want to adjust the colours and fix some images with transparent background. The theme allows also to use alternative images for dark and light theme in case some of them are not visible in dark theme. I'll follow your advice and make a separate PR for this.

Thank you!

**Review by doniks — APPROVED** [review]
Thanks @capsia37

**Comment by doniks** [comment]
Screenshot_20210617-192507_Fennec

**Comment by doniks** [comment]
Hey @capsia37 it seems that now on Firefox on android it looks as above dark blue on black... I cannot read it. Are you able to look into this?

**Pull request merged**
