### PR TITLE
Update importing-CH-urldispatcher.rst

### PR DESCRIPTION
**Pull request by lduboeuf**
url dispatcher name change with lomiri-*

### CODE REVIEW

**Review by doniks — APPROVED** [review]

**Comment by doniks** [comment]
Seems Jenkins is stuck. I've created a ticket here https://gitlab.com/ubports/ubuntu-touch/-/issues/2174

**Comment by lduboeuf** [comment]
> Seems Jenkins is stuck. I've created a ticket here https://gitlab.com/ubports/ubuntu-touch/-/issues/2174

Yes Jenkins have issues nowadays, yhe team is taking care of it

**Comment by sunweaver** [comment]
@lduboeuf Looks like Jenkins is up and running again, however this PR never landed properly in CI. Can you do some force-push to the PR branch? (Or close this PR and open it anew, so Jenkins sees it as a new PR/branch?). I tried to launch the CI builds manually, but the PR has not arrived properly in Jenkins, it seems.

**Comment by doniks** [comment]
maybe push an empty commit

**Pull request closed without merging**
