### PR TITLE
Depreciate Anbox

### PR DESCRIPTION
**Pull request by ElectrodeYT**
Adds a depreciation notice to the Anbox .rst file.

I know the other PR redirects anbox to a in-progress Waydroid doc, however it may still be a good idea to keep the Anbox documentation files, as there may be edge cases (on some older UT devices?) where keeping docs up for Anbox may be a good idea.

### CODE REVIEW

**Comment by doniks** [comment]
I'm hesitant to keep historic documentation around. There isn't a lot of contributions to even maintain the stuff that is still current and I think it will be worse for out of date information. Git doesn't forget. I admit this is not very accessible, but if people want to pass around links that's always an option.

**Comment by ElectrodeYT** [comment]
I understand. Maybe one could replace the entire anbox.rst file with a warning (and a link to Waydroid) instead? While it would accomplish the same as redirecting, it would make it more obvious that documentation once existed. This would also serve to make people aware that Anbox _was_ deprecated, rather than maybe wonder why they got linked to Waydroid instead, and try to find other Anbox documentation instead.

**Comment by ElectrodeYT** [comment]
> So, my preference would be #561 seeing that anbox upstream basically deprecated it

I wasn't going to try and "replace" 561, now that I think about it, I should have probably left a comment there instead of this...

**Comment by doniks** [comment]
fwiw, there is a redirect if someone has an old anbox link 
https://ci.ubports.com/job/docs.ubports.com/job/PR-561/5/artifact/_build/html/userguide/dailyuse/anbox.html

https://github.com/ubports/docs.ubports.com/pull/561/files#diff-16a7306e360a4be94a15010b4f83525862b470053920dc7436ecb9532a019c4cR20

**Comment by ElectrodeYT** [comment]
Closing as this is better in the discussion for the Waydroid docs PR.

**Pull request closed without merging**
