### PR TITLE
Edit images links

### PR DESCRIPTION
**Pull request by Bolly**
Fix broken links on legacy Android devices.
Fix https://github.com/ubports/docs.ubports.com/issues/388

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
No one has replied telling me if these images work or not. That's the only warning I can give, but otherwise this is mergeable.

**Comment by doniks** [comment]
Mhm. I found all four images on web.archive.org I can download them and compare md5's. I think then we should be good. 

Maybe we want to be more explicit about the provenance. I suggest to append to  

BE VERY CAREFUL! You are responsible for your own actions!

the following statement:

The ROM's below were not created by UBports and the source code for them is not available. UBports merely hosts these files on their servers, since the original links have disappeared.

**Comment by doniks** [comment]
@UniversalSuperBox since we are at it already -  shouldn't we lift the arale image from it's original server as well? Might be better to be safe than sorry. We are the only organization that has any vested interest in these files, so only fair to host them ourselves

**Comment by Bolly** [comment]
Tested image of Cooler by a user of the Spanish Telegram group.
And if we fix the links one by one? When we have confirmation that one is working we will fix it.

**Comment by doniks** [comment]
thanks @Bolly for that confirmation. 

I finally managed to download the images from the wayback machine. 

**krillin** and **vegata** images have the same md5 (below) as the ones that are on cdimage now. 

**cooler** images also seem to be the same. zip's have different md5's but seems one is just repackaged in a subfolder, all the files inside the zip have the same md5.

**frieza** has different versions. wayback machine has build_number 8 while cdimage has 4 (see diff below). @UniversalSuperBox Any idea of whether we rather want one or the other?

```
peter@hp:~/docs/bq$ diff cdimage.ubports.com/stock-bq-images/frieza-image-stable-4.zip.d/ubuntu.img.raw.d/etc/system-image/ web.archive.org/web/20200820100648/https\:/storage.googleapis.com/otas/2015/Tablets/Freezer\ FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip.d/ubuntu.img.raw.d/etc/system-image/
diff cdimage.ubports.com/stock-bq-images/frieza-image-stable-4.zip.d/ubuntu.img.raw.d/etc/system-image/channel.ini "web.archive.org/web/20200820100648/https:/storage.googleapis.com/otas/2015/Tablets/Freezer FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip.d/ubuntu.img.raw.d/etc/system-image/channel.ini"
7,8c7,8
< build_number: 4
< version_detail: ubuntu=20160524.1,device=20160523.0,custom=20160511--40-9-vivid,tag=OTA-11,version=4
---
> build_number: 8
> version_detail: ubuntu=20170127,device=20160809.0,custom=20160831--42-26-vivid,tag=OTA-15,version=8
Common subdirectories: cdimage.ubports.com/stock-bq-images/frieza-image-stable-4.zip.d/ubuntu.img.raw.d/etc/system-image/config.d and web.archive.org/web/20200820100648/https:/storage.googleapis.com/otas/2015/Tablets/Freezer FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip.d/ubuntu.img.raw.d/etc/system-image/config.d
diff cdimage.ubports.com/stock-bq-images/frieza-image-stable-4.zip.d/ubuntu.img.raw.d/etc/system-image/writable-paths "web.archive.org/web/20200820100648/https:/storage.googleapis.com/otas/2015/Tablets/Freezer FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip.d/ubuntu.img.raw.d/etc/system-image/writable-paths"
15a16
> /var/lib/biometryd-meizu-fp-reader      auto                    persistent  none        none
```

**md5:**

d8e2c1e9bd602f7118cdb3f3c53ac76c  ./people.canonical.com/~alextu/tangxi/684.zip

5dc0fc546aff0efe7fcfbe2b8dbe4dee  ./web.archive.org/web/20200820100911/https:/storage.googleapis.com/otas/2015/Tablets/Freezer/Ubuntu/OTA_13_FW_version/cooler-image-stable-6.zip
ebe35dda74b72bdcebc1afcec7f01172  ./web.archive.org/web/20200820100648/https:/storage.googleapis.com/otas/2015/Tablets/Freezer FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip
ababdd91bb5c1453e2cead1ae2b025e9  ./web.archive.org/web/20200820100356if_/https:/cdimage.ubports.com/ubports-installer/krillin/e45.zip
cc726055d03ea63017a57b5bc25305de  ./web.archive.org/web/20200820100403if_/https:/storage.googleapis.com/otas/2014/Smartphones/Aquaris_E5_HD/Ubuntu/VEGETA01A-S11A_BQ_L100EN_2017_170207.zip


d3d99daa934192467315ac2225e36daa  ./cdimage.ubports.com/stock-bq-images/cooler-image-stable-6.zip
96641de82b655e60b9478a195211cde7  ./cdimage.ubports.com/stock-bq-images/frieza-image-stable-4.zip
ababdd91bb5c1453e2cead1ae2b025e9  ./cdimage.ubports.com/stock-bq-images/krillin.zip
cc726055d03ea63017a57b5bc25305de  ./cdimage.ubports.com/stock-bq-images/VEGETA01A-S11A_BQ_L100EN_2017_170207.zip

**Comment by doniks** [comment]
ok. I think we can merge this as is for now. this is better than the status quo. 

I'll keep chasing @UniversalSuperBox outside of github to see whether we can/should switch back to frieza image version 8 or stick with the change to version 4 - my opinion is: if there is a good reason to change to 4, fine, otherwise stick with what we had for years.

Here's the links:
https://web.archive.org/web/2020*/https:/storage.googleapis.com/otas/2015/Tablets/Freezer%20FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip
https://web.archive.org/web/20200820100648/https:/storage.googleapis.com/otas/2015/Tablets/Freezer%20FHD/Ubuntu/OTA_15/frieza-image-stable-8.zip

**Review by doniks — APPROVED** [review]

**Pull request merged**
