### PR TITLE
update translations.rst

### PR DESCRIPTION
**Pull request by Danfro**
Updated information about how strings are translated (technical information as background) and on how to translate.

Please have a closer look especially at the parts regarding the forum if they are still valid. I have got no experience with this way of translations. Does this really wants to be a third way of translation? That was what the old version suggested (how I understood it anyway).

Or should the forum be given as general information only on how to get help or discuss translation?

### CODE REVIEW

**Comment by Danfro** [comment]
Ah, another point to review:

Do we really want to leave information here that translators can add their language by themselves on weblate? If yes we should include instructions. If no we should take that sentence out.

**Comment by Flohack74** [comment]
@Danfro you have to re-phrase the text a bit. We cannot accept people translating directly in the po files. It will conflict often with Weblate, and there is no automatic conflict resoultion tool. Since we do not speak all languages, and we want to have the extended history and audit trail in Weblate, to better follow wrong translations, people must not do any changes in the po files (pot is OK). Instead, they should use the more comfortable features of Weblate.
Also, in the future there will be language teams that are allowed to commit translations. All outsiders only can suggest translations, but they are not automatically committed without review.

**Comment by Danfro** [comment]
Hm, I 'thought' I left a note somewhere in there that .po translation does only apply to apps that are not translated via weblate. But, well, I can't find it. So obviously I forgot that.  :smile:
Sorry, of course that needs to be said explicitly. I will go over the text and add that information...

**Comment by Flohack74** [comment]
Can you add a link to https://translate.ubports.com/projects/ where you put the note, explaining that people can find the actual Weblate projects at this link?

**Comment by Danfro** [comment]
I do have UBports weblate linked twice already. Does it really need a third link?
But if you want to make sure people get there, of course I can do that. :+1: 

The existing links lead to [https://translate.ubports.com/](https://translate.ubports.com/) rather than to the projects page. The resulting page is pretty much the same though.

**Comment by Danfro** [comment]
Ok, all links now point to the same page and I did add another link. I hope this is that what you had in mind...

**Pull request merged**
