### PR TITLE
Insert initial info how to help documenting

### PR DESCRIPTION
**Pull request by demokrit011**

### CODE REVIEW

**Comment by NeoTheThird** [comment]
@UniversalSuperBox What's your plan with the /contribute directory? I understood that stuff like this is supposed to go into /about/introduction.rst, is that right?

**Comment by demokrit011** [comment]
I was not pinged however i just realised that the actual Plan was to make something like /contribute/documenting/ and inside this folder my changes would better fit inside a document maybe called wiki.rst? Should i close the PR and change this?

**Comment by NeoTheThird** [comment]
Let's wait for @UniversalSuperBox to comment on this, he's kind of taking the lead on this

**Comment by UniversalSuperBox** [comment]
I've started writing this page locally, but haven't finished and got caught up in other things last night. I'll send it tonight, whether it's to the forums or to this repository.

Thank you for writing this, I'll include some of it in the page that I'm writing.

**Comment by demokrit011** [comment]
Okay, i'll close the PR then, nice work!

**Pull request closed without merging**
