### PR TITLE
update deprecated method

### PR DESCRIPTION
**Pull request by ivoxavier**
The add_stylesheet() is deprecated. Changed code to match newer method

### CODE REVIEW

**Comment by doniks** [comment]
thanks. but I have no clue what this file or your change do ... can you elaborate what this fixes?

**Comment by ivoxavier** [comment]
Hi doniks,

When building read the docs on my laptop, I'm getting a warning on the terminal indicating that the method add_stylesheet() is depreceated. Change it to add_css_file() clean the warning

**Comment by doniks** [comment]
> Hi doniks,
> 
> When building read the docs on my laptop, I'm getting a warning on the terminal indicating that the method add_stylesheet() is depreceated. Change it to add_css_file() clean the warning

gotcha!

**Comment by doniks** [comment]
thx!

**Pull request merged**
