### PR TITLE
Delete documentation-todo.rst

### PR DESCRIPTION
**Pull request by NeoTheThird**
It's maybe better to use github issues for this...

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Okay. :(

Would you prefer the `..todo::` directive stayed in the documentation, or do you want all of them removed as well?

**Comment by NeoTheThird** [comment]
Dunno, just saw that that file was empty... What's the upside of using the todo directives?

**Comment by UniversalSuperBox** [comment]
They create an entry on https://docs.ubports.com/en/latest/contribute/documentation-todo.html, which will lead back to the page. Without `..todolist::`, they simply make an orange message like in https://docs.ubports.com/en/latest/porting/building-ubports-boot.html#index-0

**Comment by UniversalSuperBox** [comment]
Wrong button -_-

**Comment by NeoTheThird** [comment]
Hmm... If you wanna keep it, don't merge it.

**Comment by NeoTheThird** [comment]
Ok, yeah, I see, it's probably fine. I see how it could be handy. But we should document when to use todos and when to use issues somewhere.

**Pull request closed without merging**
